### ISSUE TITLE
Health Tab

### ISSUE THREAD

**Issue by ardeay** [zesty-io/live-editor#36]
- Run lighthouse score
- Link to w3c validator https://validator.w3.org/
- CSS validation https://jigsaw.w3.org/css-validator/
- Section 508 compliance https://www.section508.gov/test/web-software/

**Comment by darwin808** [comment]
@ardeay as I check the https://www.npmjs.com/package/lighthouse generate a json file which can be call from backend api

**Comment by darwin808** [comment]
![image](https://user-images.githubusercontent.com/71545960/173064299-ce4c1226-7d0c-42a6-9424-d259732ec305.png)
![image](https://user-images.githubusercontent.com/71545960/173064329-63dfcbd3-530e-47b7-a284-36c5221da994.png)
