### ISSUE TITLE
Field "type" and "content length" should move to the code helper tab

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/live-editor#60]
Currently, there are 2 field type values being output: string, object
Neither of these are field types in the Manager which can be very confusing for the user. The type should be the value of the field type selected in Schema.

**Comment by giseleblair** [comment]
Type column should be moved into the code helper. Get field type information by making a request to the REST API against the field itself to get the field type.

**Comment by ardeay** [comment]
change content length to "char length"
