### ISSUE TITLE
Node issue with npm install 

### ISSUE THREAD

**Issue by ardeay** [zesty-io/live-editor#96]
![image](https://user-images.githubusercontent.com/729972/181097921-386852a4-b93a-4a69-8e9d-328d258df28b.png)

**Comment by darwin808** [comment]
@ardeay  

I only allow node v14 to work in this project because some dependencies conflict with node v16

## Solution

they can use nvm to switch to version node v14

**Comment by ardeay** [comment]
Since node 18 is the current supported version, and 14 will be end of life and 2023, an alternate package should be looked for or that functionality should be replaced.

**Comment by ardeay** [comment]
Node version life cycles https://nodejs.org/en/about/releases/

**Comment by darwin808** [comment]
noted 

Ill convert it to 16
